# Generated by Django 5.1.5 on 2025-01-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("pharmacist", "pharmacist"),
                    ("user", "user"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
