# Generated by Django 5.1.4 on 2025-01-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="delivery_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pharmacies/"),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
