# Generated by Django 5.1.5 on 2025-01-16 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0003_category_medication_pharmacist"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pharmacist",
            name="license_image",
            field=models.ImageField(blank=True, null=True, upload_to="licenses/"),
        ),
        migrations.AlterField(
            model_name="pharmacist",
            name="license_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
