# Generated by Django 5.0.6 on 2025-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_category_medication_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(default=11.5742),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(default=37.3614),
        ),
    ]
