# Generated by Django 5.0.6 on 2025-01-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_pharmacy_latitude_alter_pharmacy_longitude'),
        ('pharmacy', '0004_pharmacist_created_at_pharmacist_license_image_and_more'),
    ]

    operations = [
    ]
