# Generated by Django 5.0.6 on 2025-01-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_merge_20250120_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
