# Generated by Django 5.0.6 on 2025-02-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_review'),
        ('pharmacy', '0007_subscription'),
    ]

    operations = [
    ]
