# Generated by Django 5.1.5 on 2025-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
