# Generated by Django 5.0.6 on 2025-02-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='medication',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='medication_name',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('name', 'manufacturer', 'expiry_date', 'pharmacy')},
        ),
    ]
