# Generated by Django 5.0.6 on 2025-02-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_remove_searchhistory_medication_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('name', 'manufacturer', 'expiry_date')},
        ),
        migrations.AddField(
            model_name='medication',
            name='batch_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
